### ISSUE TITLE
Is there a testing or validation report for USB3-HUB? 

### ISSUE THREAD

**Issue by EdXian** [IanHarris6/USB3-HUB#1]
Hi @IanHarris6 ,

Nice to meet you. I'm glad to see the project shared by you!

I wanna know have you ever test or valid the usb 3 speed for your board? 
Also, I want to know if i have permission to manufacture the board for personal DIY project?

Best Regard,
Edxian

**Comment by IanHarris6** [comment]
Hi Edxian,

Great to hear from you.

I have not tested or simulated the usb3 speed for this board. I have not
even ordered or assembled the board myself. However, I have done a fair
amount of research into via placement and have the GND planes beneath all
the differential pairs. If you’d to look into it yourself most of my
sources are under the .txt file in the repository.

And do you have permission to build it yourself? Of course! Please do. I
should note I have not finished adding silkscreen to label all of the
components on the PCB.

I kept all the components on one layer whole reducing manufacturing
difficulty in mind.

Also, there are only 2 USBA downstream ports. I briefly considered adding 2
more and rearranging the placement of the 4 USBA receptacles. So let me
know if you would like help with this or if you have any other questions.

Kind regards,
Ian

**Comment by EdXian** [comment]
Hi @IanHarris6 ,

It's my pleasure to help you!

I have read the text file you mentioned about. I would like to help you check the impedance control for each differential pair and routing. First, I will make a hand-made circuit board(assemble the component by myself). Second, PCBA will be processed if testing is okay. 

Since I don't have experience in Kicad, It may take me some time to check.

Best Regards,
Edxian

**Comment by IanHarris6** [comment]
Edxian, thank you! That would be super helpful and much appreciated.

Do you need anything to create your handmade circuit board? Like gerber
files? Or pdfs of each layer of the PCB? I know Kicad pretty well so I can
get these things for you.

Kind regards,
Ian

**Comment by EdXian** [comment]
Hi @IanHarris6 ,

Can you please kindly provide BOM list?  I want to check all components are "in stock" 
and can be shipped immediately.

Best Regards,
Edxian

**Comment by IanHarris6** [comment]
Hi Edxian,

Here is a google sheets link to the BOM spreadsheet… I’ll be able to put it
in the repository later today.

https://docs.google.com/spreadsheets/d/1NChWdBp-OVCa81FMLSUoy8bJFvOtNQILqIGQjKQwoyY/edit


Kind regards,
Ian

**Comment by IanHarris6** [comment]
Let me know if you have trouble opening up the spreadsheet.

**Comment by EdXian** [comment]
HI @IanHarris6 ,

I have just read the Google sheet. I think it is well prepared now. Could you please help me release the final gerber file and schematic on the github？

Best regards, 
Edxian

**Comment by IanHarris6** [comment]
@EdXian 
I will update the silkscreen and make a few small edits where I see necessary... Then I will add these gerbers under [/Gerber Files](https://github.com/IanHarris6/USB3-HUB/tree/main/Gerber%20Files) sometime tonight.

I am happy to provide anything else you need. I really hope this works out for you.

Ian

**Comment by EdXian** [comment]
Hi @IanHarris6 ,

Which approach do you use to calculate the impedance control ? By JLCPCB impedance Calculator or the kicad built-in calculator?

BTW, Since the standard process for 4 layer is JLC7628. it cost you less money for choosing JLC7628  than choosing JLC3313.
![image](https://github.com/IanHarris6/USB3-HUB/assets/28064159/e5485fb2-8787-4e8d-89f2-27313cb9711b)

Best Regards,
Xian

**Comment by IanHarris6** [comment]
Thanks for the comment... I have just updated the gerbers and Kicad files in the Repo... and to answer your question I used the Kicad Calculator. I did not realize JLC7628 was less money. My impedance calculations use JLC3313 stack up. I believe there are some sources in my notes about why I chose Kicad calculator over jlcpcb calculator. If you would like we can continue this conversation elsewhere and close this issue? My email is nxgpelo@gmail.com or you can message me on discord @Ian5926.

I will look into changing the stack up tomorrow evening if necessary and I also want to see if adding stitching VIAS is a good idea.

Kind regards,
Ian

**Comment by EdXian** [comment]
Hi @IanHarris6 ,

Let's close the issue and move the topic to discord.  I've sent the invitation to your discord account.

Best Regards,
Xian
